import authors from "./authors";

const series = [
  {
    id: "harry-potter",
    title: "Harry Potter",
    description:
      "The Harry Potter book series, written by J.K. Rowling, follows the journey of a young wizard, Harry Potter, as he discovers his place in the magical world and faces challenges to defeat the evil wizard Lord Voldemort. Over the course of seven books, Harry and his friends, Hermione Granger and Ron Weasley, explore magic, face dangers, and learn about friendship, courage, and the power of choice in an epic struggle between good and evil. ",
    author: authors[0],
    year: 1997,
    image:
      "https://ingresso-a.akamaihd.net/b2b/production/uploads/article/image/2549/7ababc2015043445b750ebc853a5f706.jpg",
    books: [
      {
        id: "harry-potter-and-the-philosopher's-stone",
        title: "Harry Potter and the Philosopher's Stone",
        author: authors[0],
        year: 1997,
        order: 1,
        image: "https://m.media-amazon.com/images/I/81pB+joKL4L._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96G4?ref_=dbs_p_pwh_rwt_anx_cl_0&storeType=ebooks",
      },
      {
        id: "harry-potter-and-the-chamber-of-secrets",
        title: "Harry Potter and the Chamber of Secrets",
        author: authors[0],
        year: 1998,
        order: 2,
        image: "https://m.media-amazon.com/images/I/81D+5aMHzFL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96K0?ref_=dbs_p_pwh_rwt_anx_cl_1&storeType=ebooks",
      },
      {
        id: "harry-potter-and-the-prisoner-of-azkaban",
        title: "Harry Potter and the Prisoner of Azkaban",
        author: authors[0],
        year: 1999,
        order: 3,
        image: "https://m.media-amazon.com/images/I/81Q+2zleuwL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96HI?ref_=dbs_p_pwh_rwt_anx_cl_2&storeType=ebooks",
      },
      {
        id: "harry-potter-and-the-goblet-of-fire",
        title: "Harry Potter and the Goblet of Fire",
        author: authors[0],
        year: 2000,
        order: 4,
        image: "https://m.media-amazon.com/images/I/81IsnaNraBL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96FA?ref_=dbs_p_pwh_rwt_anx_cl_3&storeType=ebooks",
      },
      {
        id: "harry-potter-and-the-order-of-the-phoenix",
        title: "Harry Potter and the Order of the Phoenix",
        author: authors[0],
        year: 2003,
        order: 5,
        image: "https://m.media-amazon.com/images/I/81ZQUV67MGL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96IC?ref_=dbs_p_pwh_rwt_anx_cl_4&storeType=ebooks",
      },
      {
        id: "harry-potter-and-the-half-blood-prince",
        title: "Harry Potter and the Half-Blood Prince",
        author: authors[0],
        year: 2005,
        order: 6,
        image: "https://m.media-amazon.com/images/I/81SZC96OGOL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96LY?notRedirectToSDP=1&ref_=dbs_mng_calw_5&storeType=ebooks",
      },
      {
        id: "harry-potter-and-the-deathly-hallows",
        title: "Harry Potter and the Deathly Hallows",
        author: authors[0],
        year: 2007,
        order: 7,
        image: "https://m.media-amazon.com/images/I/81PbdwXqKkL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96GE?notRedirectToSDP=1&ref_=dbs_mng_calw_6&storeType=ebooks",
      },
      {
        id: "harry-potter-and-the-cursed-child",
        title: "Harry Potter and the Cursed Child",
        author: authors[0],
        year: 2016,
        order: 8,
        image: "https://rocco.com.br/app/uploads/2024/04/9786555322682.jpg",
        link: "https://www.amazon.com.br/Harry-Potter-Crian%C3%A7a-Amaldi%C3%A7oada-Parte/dp/8532530435",
      },
    ],
  },
  {
    id: "the-lord-of-the-rings",
    title: "The Lord of the Rings",
    description:
      "The Lord of the Rings trilogy, written by J.R.R. Tolkien, narrates the epic adventure of Frodo Baggins, a hobbit who is entrusted with the mission of destroying the powerful One Ring and preventing it from falling into the hands of the dark Lord Sauron. Accompanied by a diverse group of heroes, Frodo faces battles, supernatural dangers, and temptations on a journey that explores themes of courage, sacrifice, and friendship. The story celebrates the fight between good and evil in a vast and detailed fantasy world, Middle-earth.",
    author: authors[1],
    year: 1954,
    image:
      "https://cinepop.com.br/wp-content/uploads/2021/12/o-senhor-dos-aneis.jpg",
    books: [
      {
        id: "the-fellowship-of-the-ring",
        title: "The Fellowship of the Ring",
        author: authors[1],
        year: 1954,
        order: 1,
        image: "https://m.media-amazon.com/images/I/81SM0D5+DwL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B0B3C98K98?ref_=dbs_p_pwh_rwt_cpsb_cl_0&storeType=ebooks",
      },
      {
        id: "the-two-towers",
        title: "The Two Towers",
        author: authors[1],
        year: 1954,
        order: 2,
        image: "https://m.media-amazon.com/images/I/81N9hxO6XdL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B0B3CCH4XF?ref_=dbs_p_pwh_rwt_cpsb_cl_1&storeType=ebooks",
      },
      {
        id: "the-return-of-the-king",
        title: "The Return of the King",
        author: authors[1],
        year: 1955,
        order: 3,
        image: "https://m.media-amazon.com/images/I/81LUEEYfQNL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B0B3D2GFXN?ref_=dbs_p_pwh_rwt_cpsb_cl_2&storeType=ebooks",
      },
    ],
  },
  {
    id: "a-song-of-ice-and-fire",
    title: "A Song of Ice and Fire",
    description:
      "A Song of Ice and Fire, a series written by George R.R. Martin, follows the battle for the Iron Throne in Westeros, a continent marked by rivalries, alliances, and betrayals. Noble families like the Starks, Lannisters, and Targaryens engage in a dangerous game of intrigues, where power and survival go hand in hand. While kings and queens fight for control of the Seven Kingdoms, an ancient threat rises in the north, and winter approaches, bringing with it the danger of the White Walkers. The series explores themes of power, loyalty, and morality in a complex narrative full of twists and turns.",
    author: authors[2],
    year: 1996,
    image:
      "https://img.odcdn.com.br/wp-content/uploads/2024/07/Design-sem-nome-16-1-scaled.jpg",
    books: [
      {
        id: "a-game-of-thrones",
        title: "A Game of Thrones",
        author: authors[2],
        year: 1996,
        order: 1,
        image: "https://m.media-amazon.com/images/I/91eHityofNL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B07PPB9QW1?ref_=dbs_p_pwh_rwt_anx_cl_0&storeType=ebooks",
      },
      {
        id: "a-clash-of-kings",
        title: "A Clash of Kings",
        author: authors[2],
        year: 1998,
        order: 2,
        image: "https://m.media-amazon.com/images/I/91N6C0jwzuL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B07QYPLKV1?ref_=dbs_p_pwh_rwt_anx_cl_1&storeType=ebooks",
      },
      {
        id: "a-storm-of-swords",
        title: "A Storm of Swords",
        author: authors[2],
        year: 2000,
        order: 3,
        image: "https://m.media-amazon.com/images/I/91VVZ-v5GYL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B07QXSYDSB?ref_=dbs_p_pwh_rwt_anx_cl_2&storeType=ebooks",
      },
      {
        id: "a-feast-for-crows",
        title: "A Feast for Crows",
        author: authors[2],
        year: 2019,
        order: 4,
        image: "https://m.media-amazon.com/images/I/814UZhEYFfL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B081284MLJ?notRedirectToSDP=1&ref_=dbs_mng_calw_3&storeType=ebooks",
      },
      {
        id: "a-dance-with-dragons",
        title: "A Dance with Dragons",
        author: authors[2],
        year: 2020,
        order: 5,
        image: "https://m.media-amazon.com/images/I/91DisjRjFxL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B084SS25D3?notRedirectToSDP=1&ref_=dbs_mng_calw_4&storeType=ebooks",
      },
    ],
  },
];

export default series;
