import authors from "./authors.js";

const series = [
  {
    id: "harry-potter",
    title: "Harry Potter",
    description:
      "The Harry Potter book series, written by J.K. Rowling, follows the journey of a young wizard, Harry Potter, as he discovers his place in the magical world and faces challenges to defeat the evil wizard Lord Voldemort. Over the course of seven books, Harry and his friends, Hermione Granger and Ron Weasley, explore magic, face dangers and learn about friendship, courage and the power of choice in an epic struggle between good and evil. ",
    author: authors[0],
    year: 1997,
    image:
      "https://ingresso-a.akamaihd.net/b2b/production/uploads/article/image/2549/7ababc2015043445b750ebc853a5f706.jpg",
    livros: [
      {
        id: "harry-potter-and-the-philosophers-stone",
        title: "Harry Potter and the Philosopher's Stone",
        author: authors[0],
        year: 1997,
        order: 1,
        image: "https://m.media-amazon.com/images/I/81pB+joKL4L._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96G4?ref_=dbs_p_pwh_rwt_anx_cl_0&storeType=ebooks",
      },
      {
        id: "harry-potter-and-the-chamber-of-secrets",
        title: "Harry Potter and the Chamber of Secrets",
        author: authors[0],
        year: 1998,
        order: 2,
        image: "https://m.media-amazon.com/images/I/81D+5aMHzFL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96K0?ref_=dbs_p_pwh_rwt_anx_cl_1&storeType=ebooks",
      },
      {
        id: "harry-potter-and-the-prisoner-of-azkaban",
        title: "Harry Potter and the Prisoner of Azkaban",
        author: authors[0],
        year: 1999,
        order: 3,
        image: "https://m.media-amazon.com/images/I/81Q+2zleuwL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96HI?ref_=dbs_p_pwh_rwt_anx_cl_2&storeType=ebooks",
      },
      {
        id: "harry-potter-and-the-goblet-of-fire",
        title: "Harry Potter and the Goblet of Fire",
        author: authors[0],
        year: 2000,
        order: 4,
        image: "https://m.media-amazon.com/images/I/81IsnaNraBL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96FA?ref_=dbs_p_pwh_rwt_anx_cl_3&storeType=ebooks",
      },
      {
        id: "harry-potter-and-the-order-of-the-phoenix",
        title: "Harry Potter and the Order of the Phoenix",
        author: authors[0],
        year: 2003,
        order: 5,
        image: "https://m.media-amazon.com/images/I/81ZQUV67MGL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96IC?ref_=dbs_p_pwh_rwt_anx_cl_4&storeType=ebooks",
      },
      {
        id: "harry-potter-and-the-half-blood-prince",
        title: "Harry Potter and the Half-Blood Prince",
        author: authors[0],
        year: 2005,
        order: 6,
        image: "https://m.media-amazon.com/images/I/81SZC96OGOL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96LY?notRedirectToSDP=1&ref_=dbs_mng_calw_5&storeType=ebooks",
      },
      {
        id: "Harry Potter and the Deathly Hallows",
        title: "Harry Potter and the Deathly Hallows",
        author: authors[0],
        year: 2007,
        order: 7,
        image: "https://m.media-amazon.com/images/I/81PbdwXqKkL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B01LQM96GE?notRedirectToSDP=1&ref_=dbs_mng_calw_6&storeType=ebooks",
      },
      {
        id: "harry-potter-and-the-cursed-child",
        title: "Harry Potter and the Cursed Child",
        author: authors[0],
        year: 2016,
        order: 8,
        image: "https://rocco.com.br/app/uploads/2024/04/9786555322682.jpg",
        link: "https://www.amazon.com.br/Harry-Potter-Crian%C3%A7a-Amaldi%C3%A7oada-Parte/dp/8532530435",
      },
    ],
  },
  {
    id: "the-lord-of-the-rings",
    title: "The Lord of the Rings",
    description:
      "The Lord of the Rings, written by J.R.R. Tolkien, tells the story of the quest to destroy the One Ring, a powerful artifact created by the Dark Lord Sauron to rule over Middle-earth. The story follows Frodo Baggins, a hobbit, and his companions as they journey through dangerous lands to Mount Doom, where the Ring was forged, in order to destroy it and defeat Sauron. Along the way, they face battles, betrayal and the lure of power, as they fight to save Middle-earth from darkness. The series explores themes of heroism, friendship and the struggle between good and evil in a richly imagined world.",
    author: authors[1],
    year: 1954,
    image:
      "https://cinepop.com.br/wp-content/uploads/2021/12/o-senhor-dos-aneis.jpg",
    livros: [
      {
        id: "the-fellowship-of-the-ring",
        title: "the Fellowship of the Ring",
        author: authors[1],
        year: 1954,
        order: 1,
        image: "https://m.media-amazon.com/images/I/81SM0D5+DwL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B0B3C98K98?ref_=dbs_p_pwh_rwt_cpsb_cl_0&storeType=ebooks",
      },
      {
        id: "the-two-towers",
        title: "The Two Towers",
        author: authors[1],
        year: 1954,
        order: 2,
        image: "https://m.media-amazon.com/images/I/81N9hxO6XdL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B0B3CCH4XF?ref_=dbs_p_pwh_rwt_cpsb_cl_1&storeType=ebooks",
      },
      {
        id: "the-return-of-the-king",
        title: "The Return of the King",
        author: authors[1],
        year: 1955,
        order: 3,
        image: "https://m.media-amazon.com/images/I/81LUEEYfQNL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B0B3D2GFXN?ref_=dbs_p_pwh_rwt_cpsb_cl_2&storeType=ebooks",
      },
    ],
  },
  {
    id: "a-song-of-ice-and-fire",
    title: "A Song of Ice and Fire",
    description:
      "A Song of Ice and Fire, written by George R.R. Martin, is a series of epic fantasy novels set in the fictional world of Westeros and Essos. The series follows the power struggles between noble families as they vie for control of the Iron Throne and the Seven Kingdoms. The story is told from multiple perspectives, with a large cast of characters, and explores themes of politics, power, war, and the human heart in conflict with itself. The series is known for its complex characters, intricate plotting, and unpredictable twists and turns.",
    author: authors[2],
    year: 1996,
    image:
      "https://img.odcdn.com.br/wp-content/uploads/2024/07/Design-sem-nome-16-1-scaled.jpg",
    livros: [
      {
        id: "a-game-of-thrones",
        title: "A Game of Thrones",
        author: authors[2],
        year: 1996,
        order: 1,
        image: "https://m.media-amazon.com/images/I/91eHityofNL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B07PPB9QW1?ref_=dbs_p_pwh_rwt_anx_cl_0&storeType=ebooks",
      },
      {
        id: "a-clash-of-kings",
        title: "A Clash of Kings",
        author: authors[2],
        year: 1998,
        order: 2,
        image: "https://m.media-amazon.com/images/I/91N6C0jwzuL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B07QYPLKV1?ref_=dbs_p_pwh_rwt_anx_cl_1&storeType=ebooks",
      },
      {
        id: "the-storm-of-swords",
        title: "The Storm of Swords",
        author: authors[2],
        year: 2000,
        order: 3,
        image: "https://m.media-amazon.com/images/I/91VVZ-v5GYL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B07QXSYDSB?ref_=dbs_p_pwh_rwt_anx_cl_2&storeType=ebooks",
      },
      {
        id: "a-feast-for-crows",
        title: "A Feast for Crows",
        author: authors[2],
        year: 2019,
        order: 4,
        imagem: "https://m.media-amazon.com/images/I/814UZhEYFfL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B081284MLJ?notRedirectToSDP=1&ref_=dbs_mng_calw_3&storeType=ebooks",
      },
      {
        id: "a-dance-with-dragons",
        title: "A Dance with Dragons",
        author: authors[2],
        year: 2020,
        order: 5,
        imagem: "https://m.media-amazon.com/images/I/91DisjRjFxL._SL1500_.jpg",
        link: "https://www.amazon.com.br/gp/product/B084SS25D3?notRedirectToSDP=1&ref_=dbs_mng_calw_4&storeType=ebooks",
      },
    ],
  },
];

export default series;
